# Generated by Django 3.1.2 on 2021-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, max_length=200, null=True)),
                ('votes', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'table2',
                'managed': False,
            },
        ),
    ]
